- name: Configure webserver with nginx
  hosts: controller
  become: True
  tasks:
    - name: Habilitar repositorio crb
      ansible.builtin.dnf:
        name: centos-release-openstack-yoga
        enablerepo: crb
        state: present        
 #   - name: Instalar paquetes de openstack
 #     package: name=centos-release-openstack-yoga update_cache=yes
    - name: Actualizar paquetes
      ansible.builtin.dnf:
        name: "*"
        state: latest
